/*
 * The MIT License
 *
 * Copyright 2014 David Miserez <davidmiserez at gmail.com>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package swing.dialog;

import swing.Slyum;

/**
 * @author David Miserez
 */
public class DialogDeleteView extends javax.swing.JDialog {

  public static boolean show(String viewName, String[] componentsDeleted) {
    DialogDeleteView dialog = new DialogDeleteView(viewName, componentsDeleted);
    dialog.setLocationRelativeTo(null);
    dialog.setVisible(true);
    return dialog.accepted;
  }

  private boolean accepted = false;

  /**
   * Creates new form DialogDeleteView
   *
   * @param viewName the name of the view.
   * @param componentsDeleted A list of components that will be displayed in the dialog.
   */
  private DialogDeleteView(String viewName, String[] componentsDeleted) {
    super(Slyum.getInstance(), true);
    initComponents();
    lblDescription.setText(lblDescription.getText().replace("$", viewName));

    String strComponentsDeleted;

    if (componentsDeleted.length == 0)
      strComponentsDeleted =
          "No component in the view will be deleted.";
    else
      strComponentsDeleted =
          "The following components are only existing in this vew:\n";

    for (String strC : componentsDeleted)
      strComponentsDeleted += "\n  - " + strC;

    txtComponentsDeleted.setText(strComponentsDeleted);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblIcon = new javax.swing.JLabel();
    lblDescription = new javax.swing.JLabel();
    btnCancel = new javax.swing.JButton();
    btnDelete = new javax.swing.JButton();
    scrollPane = new javax.swing.JScrollPane();
    txtComponentsDeleted = new javax.swing.JTextArea();
    lblDescription2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Slyum - Delete view");
    setModal(true);
    setResizable(false);

    lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/resources/icon/warning.png"))); // NOI18N

    lblDescription.setText("Are you sure you want to delete the view \"$\"?");

    btnCancel.setText("Cancel");
    btnCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelActionPerformed(evt);
      }
    });

    btnDelete.setText("Delete");
    btnDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDeleteActionPerformed(evt);
      }
    });

    txtComponentsDeleted.setEditable(false);
    txtComponentsDeleted.setColumns(20);
    txtComponentsDeleted.setLineWrap(true);
    txtComponentsDeleted.setRows(5);
    txtComponentsDeleted.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
    txtComponentsDeleted.setOpaque(false);
    scrollPane.setViewportView(txtComponentsDeleted);

    lblDescription2.setText("This action can't be undone (a save will automatically be performed).");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                              .addComponent(scrollPane)
                                              .addGroup(layout.createSequentialGroup()
                                                              .addComponent(lblIcon)
                                                              .addPreferredGap(
                                                                  javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                              .addGroup(layout.createParallelGroup(
                                                                                  javax.swing.GroupLayout.Alignment.LEADING)
                                                                              .addComponent(lblDescription2,
                                                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                            364, Short.MAX_VALUE)
                                                                              .addGroup(layout.createSequentialGroup()
                                                                                              .addComponent(
                                                                                                  lblDescription,
                                                                                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                  353,
                                                                                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                              .addGap(0, 0,
                                                                                                      Short.MAX_VALUE))))
                                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup()
                                                              .addGap(0, 0, Short.MAX_VALUE)
                                                              .addComponent(btnDelete)
                                                              .addPreferredGap(
                                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                              .addComponent(btnCancel)))
                              .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnDelete});

    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                              .addComponent(lblIcon)
                                              .addGroup(layout.createSequentialGroup()
                                                              .addComponent(lblDescription,
                                                                            javax.swing.GroupLayout.PREFERRED_SIZE, 14,
                                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                              .addPreferredGap(
                                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                              .addComponent(lblDescription2)))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                              .addComponent(btnCancel)
                                              .addComponent(btnDelete))
                              .addGap(4, 4, 4))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    accepted = true;
    setVisible(false);
  }//GEN-LAST:event_btnDeleteActionPerformed

  private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    accepted = false;
    setVisible(false);
  }//GEN-LAST:event_btnCancelActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnDelete;
  private javax.swing.JLabel lblDescription;
  private javax.swing.JLabel lblDescription2;
  private javax.swing.JLabel lblIcon;
  private javax.swing.JScrollPane scrollPane;
  private javax.swing.JTextArea txtComponentsDeleted;
  // End of variables declaration//GEN-END:variables
}
