package swing;

import java.util.Properties;

/**
 * @author David Miserez
 */
public class IssuesInformation extends javax.swing.JDialog {

  public static void mustDisplayMessage() {

    final int COUNT_DISPLAY_ISSUES_MESSAGE = 4;
    final String PROPERTIE_NAME = "CounterDisplayIssuesMessage";
    final Properties properties = PropertyLoader.getInstance()
                                                .getProperties();

    String prop = properties.getProperty("CounterDisplayIssuesMessage");
    if (prop == null) {
      properties.put(PROPERTIE_NAME,
                     String.valueOf(COUNT_DISPLAY_ISSUES_MESSAGE));
    } else {
      int counter = Integer.valueOf(prop);
      if (counter >= 0) {
        if (counter == 0) {
          new IssuesInformation(Slyum.getInstance(), true).setVisible(true);
        }
        properties.put(PROPERTIE_NAME, String.valueOf(--counter));
      }
    }
    PropertyLoader.getInstance().push();
  }

  /**
   * Creates new form IssuesInformation
   *
   * @param parent the parent {@link java.awt.Frame}.
   * @param modal {@code true} if it is shown as modal, or {@code false} if not.
   */
  public IssuesInformation(final java.awt.Frame parent, final boolean modal) {
    super(parent, modal);
    initComponents();
    setLocationRelativeTo(Slyum.getInstance());
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnOk = new javax.swing.JButton();
    lblImg = new javax.swing.JLabel();
    jTextArea1 = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Slyum - Informations about issues");
    setBackground(java.awt.Color.white);
    setResizable(false);

    btnOk.setText("Yea yea... leave me alone.");
    btnOk.setActionCommand("ok");
    btnOk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnOkActionPerformed(evt);
      }
    });

    lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource(Slyum.ICON_PATH + "icon_bug.png"))); // NOI18N

    jTextArea1.setEditable(false);
    jTextArea1.setColumns(20);
    jTextArea1.setLineWrap(true);
    jTextArea1.setRows(5);
    jTextArea1.setText(
        "Hi! You seem to use Slyum a lot. Nice to see that! If you encounter some bugs or disagreements, feel free to " +
        "report them from Help menu. Suggestions for enhancement are welcome too.\nThanks");
    jTextArea1.setWrapStyleWord(true);
    jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
    jTextArea1.setOpaque(false);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                              .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                              .addGroup(layout.createSequentialGroup()
                                                              .addComponent(jTextArea1,
                                                                            javax.swing.GroupLayout.PREFERRED_SIZE, 269,
                                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                              .addPreferredGap(
                                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                              .addComponent(lblImg)
                                                              .addGap(0, 0, Short.MAX_VALUE)))
                              .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                              .addComponent(lblImg)
                                              .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                              .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
    setVisible(false);
  }//GEN-LAST:event_btnOkActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnOk;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JLabel lblImg;
  // End of variables declaration//GEN-END:variables
}
