package swing;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

/**
 * This dialog display a JTextEdit for edit the content of a TextBoxCommentary.
 * 
 * @author David Miserez
 * @version 1.0 - 25.07.2011
 */
public class EditCommentaryDialog extends JDialog
{
	private static final long serialVersionUID = 1182377279614623151L;
	private boolean accepted = false;
	private final JPanel contentPanel = new JPanel();
	private JTextField textField;

	/**
	 * Create the dialog.
	 */
	public EditCommentaryDialog(String defaultText)
	{
		// Code generated by WindowBuilder from Google
		setModalityType(ModalityType.APPLICATION_MODAL);
		setTitle("Slyum - Commentary editor");
		setResizable(false);
		setBounds(100, 100, 513, 107);
		getContentPane().setLayout(new BorderLayout());
		contentPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		getContentPane().add(contentPanel, BorderLayout.CENTER);
		contentPanel.setLayout(new BoxLayout(contentPanel, BoxLayout.PAGE_AXIS));
		{
			final JLabel lblEditCommentary = new JLabel("Edit commentary :");
			contentPanel.add(lblEditCommentary);
		}
		{
			textField = new JTextField(defaultText);
			contentPanel.add(textField);
			textField.setColumns(10);
		}
		{
			final JPanel buttonPane = new JPanel();
			buttonPane.setLayout(new FlowLayout(FlowLayout.RIGHT));
			getContentPane().add(buttonPane, BorderLayout.SOUTH);
			{
				final JButton okButton = new JButton("OK");
				getRootPane().setDefaultButton(okButton);
				okButton.addActionListener(new ActionListener() {
					@Override
					public void actionPerformed(ActionEvent arg0)
					{
						accepted = true;
						setVisible(false);
					}
				});
				okButton.setActionCommand("OK");
				buttonPane.add(okButton);
				getRootPane().setDefaultButton(okButton);
			}
			{
				final JButton cancelButton = new JButton("Cancel");
				cancelButton.addActionListener(new ActionListener() {
					@Override
					public void actionPerformed(ActionEvent e)
					{
						setVisible(false);
					}
				});
				cancelButton.setActionCommand("Cancel");
				buttonPane.add(cancelButton);
			}
		}
		setLocationRelativeTo(null);
	}

	public String getText()
	{
		return textField.getText();
	}

	public boolean isAccepted()
	{
		return accepted;
	}

}
