name: Deployment

on:
  push:
    tags:
      - slyum-*

jobs:

  binaries_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: action/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: 'x64'
          cache: maven
      - name: Installer for Microsoft Windows
        run:
          - mvn -B package --file pom.xml
          - $FULL_VERSION = mvn help:evaluate -Dexpression="project.version" -q -DforceStdout
          - $VERSION = mvn help:evaluate -Dexpression="project.version" -q -DforceStdout | %{ $_.Split('-')[0]; }
          - $DESCRIPTION = mvn help:evaluate -Dexpression="project.description" -q -DforceStdout
          - $ARTIFACTID = mvn help:evaluate -Dexpression="project.artifactId" -q -DforceStdout
          - jpackage --name Slyum --type msi --main-class swing.Slyum --main-jar $ARTIFACTID-$FULL_VERSION.jar --app-version "$VERSION" --copyright "©HEIG-VD // GAPS 2023" --description "$DESCRIPTION" --about-url "https://gaps.heig-vd.ch" --input target\dist --icon tools\icns\slyum.ico --win-dir-chooser --win-menu --win-menu-group "Slyum" --win-per-user-install
        with:
          name: slyum-x64-msi
          path: "*.msi"
          retention-days: 1


#  binaries_deb:
#    runs-on: ubuntu-latest

#  binaries_rpm:
#    runs-on: ubuntu-latest

#  binaries_macos_x64:
#    runs-on: macos-latest

#  binaries_macos_aarch64:
#    runs-on: macos-latest

