name: Release Binaries

on:
  push:
    tags:
      - slyum-*

jobs:

  release_snapshots:
    name: Releasing Snapshots
    runs-on: ubuntu-latest
    steps:
      - name: Getting sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Creating variables from pom.xml
        run: |
          echo "slyum_full_version=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_ENV
          echo "slyum_version=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout | awk -F '-' '{ print $1 }'`" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.slyum_full_version }}
          release_name: Release ${{ env.slyum_full_version }}
          body_path: src/main/resources/versions/${{ env.slyum_version }}.md
          draft: false
          prerelease: false
